class Helpers {
  List<Map<String, dynamic>> sorting = [
    {'name': 'Relevancy', 'value': 'relevancy'},
    {'name': 'Popularity', 'value': 'popularity'},
    {'name': 'Date Published', 'value': 'publishedAt'},
  ];

  List<Map<String, dynamic>> languages = [
    {'language': 'English', 'symbol': 'en'},
    {'language': 'French', 'symbol': 'fr'},
    {'language': 'German', 'symbol': 'de'},
    {'language': 'Spanish', 'symbol': 'es'},
    {'language': 'Chinese', 'symbol': 'zh'},
    {'language': 'Hebrew', 'symbol': 'he'},
    {'language': 'Italian', 'symbol': 'it'},
    {'language': 'Dutch', 'symbol': 'nl'},
    {'language': 'Norwegian', 'symbol': 'no'},
    {'language': 'Portuguese', 'symbol': 'pt'},
    {'language': 'Russian', 'symbol': 'ru'},
    {'language': 'Arabic', 'symbol': 'ar'},
  ];
  List<Map<String, dynamic>> countries = [
    {'name': 'Australia', 'symbol': 'au'},
    {'name': 'Austria', 'symbol': 'at'},
    {'name': 'Belgium', 'symbol': 'be'},
    {'name': 'Brazil', 'symbol': 'br'},
    {'name': 'Bulgaria', 'symbol': 'bg'},
    {'name': 'Colombia', 'symbol': 'co'},
    {'name': 'Cuba', 'symbol': 'cu'},
    {'name': 'Czech Republic', 'symbol': 'cz'},
    {'name': 'Egypt', 'symbol': 'eg'},
    {'name': 'France', 'symbol': 'fr'},
    {'name': 'Germany', 'symbol': 'de'},
    {'name': 'Greece', 'symbol': 'gr'},
    {'name': 'Hong Kong', 'symbol': 'hk'},
    {'name': 'Hungary', 'symbol': 'hu'},
    {'name': 'India', 'symbol': 'in'},
    {'name': 'Indonesia', 'symbol': 'id'},
    {'name': 'Ireland', 'symbol': 'ie'},
    {'name': 'Israel', 'symbol': 'il'},
    {'name': 'Italy', 'symbol': 'it'},
    {'name': 'Japan', 'symbol': 'jp'},
    {'name': 'Latvia', 'symbol': 'lv'},
    {'name': 'Lithuania', 'symbol': 'lt'},
    {'name': 'Malaysia', 'symbol': 'my'},
    {'name': 'Mexico', 'symbol': 'mx'},
    {'name': 'Morocco', 'symbol': 'ma'},
    {'name': 'Netherlands', 'symbol': 'nl'},
    {'name': 'New Zealand', 'symbol': 'nz'},
    {'name': 'Nigeria', 'symbol': 'ng'},
    {'name': 'Norway', 'symbol': 'no'},
    {'name': 'Philippines', 'symbol': 'ph'},
    {'name': 'Portugal', 'symbol': 'pl'},
    {'name': 'Romania', 'symbol': 'ro'},
    {'name': 'Russia', 'symbol': 'ru'},
    {'name': 'Saudi Arabia', 'symbol': 'sa'},
    {'name': 'Serbia', 'symbol': 'rs'},
    {'name': 'Singapore', 'symbol': 'sg'},
    {'name': 'Slovakia', 'symbol': 'sk'},
    {'name': 'Slovenia', 'symbol': 'si'},
    {'name': 'South Africa', 'symbol': 'za'},
    {'name': 'South Korea', 'symbol': 'kr'},
    {'name': 'Sweden', 'symbol': 'se'},
    {'name': 'Switzerland', 'symbol': 'ch'},
    {'name': 'Taiwan', 'symbol': 'tw'},
    {'name': 'Thailand', 'symbol': 'th'},
    {'name': 'Turkey', 'symbol': 'tr'},
    {'name': 'UAE', 'symbol': 'ar'},
    {'name': 'Ukraine', 'symbol': 'ua'},
    {'name': 'UK', 'symbol': 'gb'},
    {'name': 'US', 'symbol': 'us'},
    {'name': 'Venuzuela', 'symbol': 've'},
  ];
}
